In [2]:
from pathlib import Path

import pandas as pd

ROOT_DIR = Path().resolve().parent
DATA_DIR = ROOT_DIR / "data/raw"
file_path = 'Superstore.csv'

df = pd.read_csv(DATA_DIR / file_path, encoding='latin1')
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2013-138688,13-06-2013,17-06-2013,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2012-108966,11-10-2012,18-10-2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2012-108966,11-10-2012,18-10-2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [5]:
# Convertir a datetime Order Date y Ship Date
df['Order Date'] = pd.to_datetime(df['Order Date'], format='%d-%m-%Y')
df['Ship Date'] = pd.to_datetime(df['Ship Date'], format='%d-%m-%Y')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   datetime64[ns]
 3   Ship Date      9994 non-null   datetime64[ns]
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(13)
memory usage: 1.6+ MB

In [6]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2013-152156,2013-11-09,2013-11-12,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2013-152156,2013-11-09,2013-11-12,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2013-138688,2013-06-13,2013-06-17,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2012-108966,2012-10-11,2012-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2012-108966,2012-10-11,2012-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [7]:
df['Year'] = df['Order Date'].dt.year
df['Month'] = df['Order Date'].dt.month
df['Weekday'] = df['Order Date'].dt.weekday
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Year,Month,Weekday
0,1,CA-2013-152156,2013-11-09,2013-11-12,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2013,11,5
1,2,CA-2013-152156,2013-11-09,2013-11-12,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2013,11,5
2,3,CA-2013-138688,2013-06-13,2013-06-17,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,2013,6,3
3,4,US-2012-108966,2012-10-11,2012-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2012,10,3
4,5,US-2012-108966,2012-10-11,2012-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2012,10,3

In [8]:
df['Month name'] = df['Order Date'].dt.month_name()
df['Weekday name'] = df['Order Date'].dt.day_name()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 26 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   datetime64[ns]
 3   Ship Date      9994 non-null   datetime64[ns]
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
 21  Year           9994 non-null   int32
 22  Month          9994 non-null   int32
 23  Weekday        9994 non-null   int32
 24  Month name     9994 non-null   object
 25  Weekday name   9994 non-null   object
dtypes: datetime64[ns](2), float64(3), int32(3), int64(3), object(15)
memory usage: 1.9+ MB

In [9]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Product Name,Sales,Quantity,Discount,Profit,Year,Month,Weekday,Month name,Weekday name
0,1,CA-2013-152156,2013-11-09,2013-11-12,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2013,11,5,November,Saturday
1,2,CA-2013-152156,2013-11-09,2013-11-12,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2013,11,5,November,Saturday
2,3,CA-2013-138688,2013-06-13,2013-06-17,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,2013,6,3,June,Thursday
3,4,US-2012-108966,2012-10-11,2012-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2012,10,3,October,Thursday
4,5,US-2012-108966,2012-10-11,2012-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2012,10,3,October,Thursday

In [10]:
df['Ship delay'] = (df['Ship Date'] - df['Order Date']).dt.days
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 27 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   datetime64[ns]
 3   Ship Date      9994 non-null   datetime64[ns]
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
 21  Year           9994 non-null   int32
 22  Month          9994 non-null   int32
 23  Weekday        9994 non-null   int32
 24  Month name     9994 non-null   object
 25  Weekday name   9994 non-null   object
 26  Ship delay     9994 non-null   int64
dtypes: datetime64[ns](2), float64(3), int32(3), int64(4), object(15)
memory usage: 1.9+ MB

In [11]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sales,Quantity,Discount,Profit,Year,Month,Weekday,Month name,Weekday name,Ship delay
0,1,CA-2013-152156,2013-11-09,2013-11-12,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,261.9600,2,0.00,41.9136,2013,11,5,November,Saturday,3
1,2,CA-2013-152156,2013-11-09,2013-11-12,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,731.9400,3,0.00,219.5820,2013,11,5,November,Saturday,3
2,3,CA-2013-138688,2013-06-13,2013-06-17,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,14.6200,2,0.00,6.8714,2013,6,3,June,Thursday,4
3,4,US-2012-108966,2012-10-11,2012-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,957.5775,5,0.45,-383.0310,2012,10,3,October,Thursday,7
4,5,US-2012-108966,2012-10-11,2012-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,22.3680,2,0.20,2.5164,2012,10,3,October,Thursday,7

In [12]:
df = df.drop(columns=['Row ID', 'Customer ID', 'Product ID'])
df.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer Name,Segment,Country,City,State,Postal Code,...,Sales,Quantity,Discount,Profit,Year,Month,Weekday,Month name,Weekday name,Ship delay
0,CA-2013-152156,2013-11-09,2013-11-12,Second Class,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,...,261.9600,2,0.00,41.9136,2013,11,5,November,Saturday,3
1,CA-2013-152156,2013-11-09,2013-11-12,Second Class,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,...,731.9400,3,0.00,219.5820,2013,11,5,November,Saturday,3
2,CA-2013-138688,2013-06-13,2013-06-17,Second Class,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,...,14.6200,2,0.00,6.8714,2013,6,3,June,Thursday,4
3,US-2012-108966,2012-10-11,2012-10-18,Standard Class,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,...,957.5775,5,0.45,-383.0310,2012,10,3,October,Thursday,7
4,US-2012-108966,2012-10-11,2012-10-18,Standard Class,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,...,22.3680,2,0.20,2.5164,2012,10,3,October,Thursday,7

In [13]:
df = df.drop(columns=['Country', 'Month', 'Weekday'])
df.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer Name,Segment,City,State,Postal Code,Region,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Year,Month name,Weekday name,Ship delay
0,CA-2013-152156,2013-11-09,2013-11-12,Second Class,Claire Gute,Consumer,Henderson,Kentucky,42420,South,...,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2013,November,Saturday,3
1,CA-2013-152156,2013-11-09,2013-11-12,Second Class,Claire Gute,Consumer,Henderson,Kentucky,42420,South,...,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2013,November,Saturday,3
2,CA-2013-138688,2013-06-13,2013-06-17,Second Class,Darrin Van Huff,Corporate,Los Angeles,California,90036,West,...,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,2013,June,Thursday,4
3,US-2012-108966,2012-10-11,2012-10-18,Standard Class,Sean O'Donnell,Consumer,Fort Lauderdale,Florida,33311,South,...,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2012,October,Thursday,7
4,US-2012-108966,2012-10-11,2012-10-18,Standard Class,Sean O'Donnell,Consumer,Fort Lauderdale,Florida,33311,South,...,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2012,October,Thursday,7

In [14]:
df['Quarter'] = df['Order Date'].dt.quarter
df.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer Name,Segment,City,State,Postal Code,Region,...,Product Name,Sales,Quantity,Discount,Profit,Year,Month name,Weekday name,Ship delay,Quarter
0,CA-2013-152156,2013-11-09,2013-11-12,Second Class,Claire Gute,Consumer,Henderson,Kentucky,42420,South,...,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2013,November,Saturday,3,4
1,CA-2013-152156,2013-11-09,2013-11-12,Second Class,Claire Gute,Consumer,Henderson,Kentucky,42420,South,...,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2013,November,Saturday,3,4
2,CA-2013-138688,2013-06-13,2013-06-17,Second Class,Darrin Van Huff,Corporate,Los Angeles,California,90036,West,...,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,2013,June,Thursday,4,2
3,US-2012-108966,2012-10-11,2012-10-18,Standard Class,Sean O'Donnell,Consumer,Fort Lauderdale,Florida,33311,South,...,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2012,October,Thursday,7,4
4,US-2012-108966,2012-10-11,2012-10-18,Standard Class,Sean O'Donnell,Consumer,Fort Lauderdale,Florida,33311,South,...,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2012,October,Thursday,7,4

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       9994 non-null   object
 1   Order Date     9994 non-null   datetime64[ns]
 2   Ship Date      9994 non-null   datetime64[ns]
 3   Ship Mode      9994 non-null   object
 4   Customer Name  9994 non-null   object
 5   Segment        9994 non-null   object
 6   City           9994 non-null   object
 7   State          9994 non-null   object
 8   Postal Code    9994 non-null   int64
 9   Region         9994 non-null   object
 10  Category       9994 non-null   object
 11  Sub-Category   9994 non-null   object
 12  Product Name   9994 non-null   object
 13  Sales          9994 non-null   float64
 14  Quantity       9994 non-null   int64
 15  Discount       9994 non-null   float64
 16  Profit         9994 non-null   float64
 17  Year           9994 non-null   int32
 18  Month name     9994 non-null   object
 19  Weekday name   9994 non-null   object
 20  Ship delay     9994 non-null   int64
 21  Quarter        9994 non-null   int32
dtypes: datetime64[ns](2), float64(3), int32(2), int64(3), object(12)
memory usage: 1.6+ MB

In [16]:
df.rename(columns={'Month name': 'Month', 'Weekday name': 'Weekday'}, inplace=True)
df.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer Name,Segment,City,State,Postal Code,Region,...,Product Name,Sales,Quantity,Discount,Profit,Year,Month,Weekday,Ship delay,Quarter
0,CA-2013-152156,2013-11-09,2013-11-12,Second Class,Claire Gute,Consumer,Henderson,Kentucky,42420,South,...,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2013,November,Saturday,3,4
1,CA-2013-152156,2013-11-09,2013-11-12,Second Class,Claire Gute,Consumer,Henderson,Kentucky,42420,South,...,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2013,November,Saturday,3,4
2,CA-2013-138688,2013-06-13,2013-06-17,Second Class,Darrin Van Huff,Corporate,Los Angeles,California,90036,West,...,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,2013,June,Thursday,4,2
3,US-2012-108966,2012-10-11,2012-10-18,Standard Class,Sean O'Donnell,Consumer,Fort Lauderdale,Florida,33311,South,...,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2012,October,Thursday,7,4
4,US-2012-108966,2012-10-11,2012-10-18,Standard Class,Sean O'Donnell,Consumer,Fort Lauderdale,Florida,33311,South,...,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2012,October,Thursday,7,4

In [17]:
df = df.sort_values(by='Order Date').reset_index(drop=True)
df.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer Name,Segment,City,State,Postal Code,Region,...,Product Name,Sales,Quantity,Discount,Profit,Year,Month,Weekday,Ship delay,Quarter
0,CA-2011-103800,2011-01-04,2011-01-08,Standard Class,Darren Powers,Consumer,Houston,Texas,77095,Central,...,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512,2011,January,Tuesday,4,1
1,CA-2011-112326,2011-01-05,2011-01-09,Standard Class,Phillina Ober,Home Office,Naperville,Illinois,60540,Central,...,Avery 508,11.784,3,0.2,4.2717,2011,January,Wednesday,4,1
2,CA-2011-112326,2011-01-05,2011-01-09,Standard Class,Phillina Ober,Home Office,Naperville,Illinois,60540,Central,...,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748,2011,January,Wednesday,4,1
3,CA-2011-112326,2011-01-05,2011-01-09,Standard Class,Phillina Ober,Home Office,Naperville,Illinois,60540,Central,...,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870,2011,January,Wednesday,4,1
4,CA-2011-141817,2011-01-06,2011-01-13,Standard Class,Mick Brown,Consumer,Philadelphia,Pennsylvania,19143,East,...,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840,2011,January,Thursday,7,1

In [18]:
# Reordenar columnas

df = df[['Order ID', 'Order Date', 'Ship Date', 'Ship delay', 'Year',
 'Quarter', 'Month', 'Weekday', 'Customer Name', 'Segment', 'City', 'State', 
 'Region', 'Product Name', 'Category', 'Sub-Category', 'Sales', 'Quantity', 'Discount', 
 'Profit']]

df.head()

,Order ID,Order Date,Ship Date,Ship delay,Year,Quarter,Month,Weekday,Customer Name,Segment,City,State,Region,Product Name,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,CA-2011-103800,2011-01-04,2011-01-08,4,2011,1,January,Tuesday,Darren Powers,Consumer,Houston,Texas,Central,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",Office Supplies,Paper,16.448,2,0.2,5.5512
1,CA-2011-112326,2011-01-05,2011-01-09,4,2011,1,January,Wednesday,Phillina Ober,Home Office,Naperville,Illinois,Central,Avery 508,Office Supplies,Labels,11.784,3,0.2,4.2717
2,CA-2011-112326,2011-01-05,2011-01-09,4,2011,1,January,Wednesday,Phillina Ober,Home Office,Naperville,Illinois,Central,SAFCO Boltless Steel Shelving,Office Supplies,Storage,272.736,3,0.2,-64.7748
3,CA-2011-112326,2011-01-05,2011-01-09,4,2011,1,January,Wednesday,Phillina Ober,Home Office,Naperville,Illinois,Central,GBC Standard Plastic Binding Systems Combs,Office Supplies,Binders,3.540,2,0.8,-5.4870
4,CA-2011-141817,2011-01-06,2011-01-13,7,2011,1,January,Thursday,Mick Brown,Consumer,Philadelphia,Pennsylvania,East,Avery Hi-Liter EverBold Pen Style Fluorescent ...,Office Supplies,Art,19.536,3,0.2,4.8840

In [19]:
processed_data_dir = ROOT_DIR / "data/processed"
df.to_csv(processed_data_dir / "Superstore_processed.csv", index=False, encoding='utf-8')